swagger: "2.0"
info:
  title: Checkout API Gateway
  description: Checkout API Gateway for Seven Aprons payments
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /payments:
    post:
      summary: Gets Stripe payment intent
      operationId: payments
      x-google-backend:
        address: https://australia-southeast1-seven-aprons.cloudfunctions.net/payments
      security:
        - api_key: []
      responses:
        "200":
          description: A successful response
          schema:
            type: string
    options:
      operationId: Cors enabling for payments API
      x-google-backend:
        address: https://australia-southeast1-seven-aprons.cloudfunctions.net/payments
      responses:
        "200":
          description: A successful response
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
